# Generated by Django 5.0.1 on 2024-01-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_cr',
            field=models.BooleanField(default=False),
        ),
    ]
